name: Terraform Deployment Workflow

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write   # This is required for OIDC based Role login
  contents: read    # This is required for actions/checkout

jobs:
  # This workflow contains a single job called "build"
  demo-task:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
            repo: terraform-infra-bob-24a
            branch: feature/test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::834786370659:role/github-actions-runner-tf-iam-role-dev
          role-session-name: login-session-by-github-actions

      # - uses: hashicorp/setup-terraform@v4

      - name: Run a multi-line script
        working-directory: root-module/
        run: |
          terraform init
          terraform plan -input=false -var-file=dev.tfvars 
          # terraform apply -auto-approve -input=false -var-file=dev.tfvars
          terraform destroy -auto-approve -input=false -var-file=dev.tfvars
